services:
  - mysql
version: 0.0.{build}
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
platform: x64
configuration: Release
skip_tags: true
before_build:
- cmd: >-
    source\AppVeyor\AppVeyorBeforeCompile.bat

build:
  project: source\ACE.sln
  verbosity: minimal
test_script:
 - cmd: dotnet test --diag ACETests-Server.txt --no-build "Source\ACE.Server.Tests"
 - cmd: dotnet test --diag ACETests-Database.txt --no-build "Source\ACE.Database.Tests"
artifacts:
  - path: 'Source\ACE.Server\bin\x64\Release\netcoreapp2.1\ACE*.dll'

deploy:
  release: ACE-v$(appveyor_build_version)
  description: 'Test releases of binaries to GitHub releases'
  provider: GitHub
  auth_token:
    secure: ZKXj2ehkYVw0oPyQddD6bHHy/xHfnqMmqHowDb7qG4rptm2LY9SVqF8ELjRzWE+V # your encrypted token from GitHub
  artifact: /.*\.dll/        # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: appveyortest  
